### PR TITLE
All the recent Biopython update talks

### PR DESCRIPTION
**Pull request by peterjc**
Could you **rebase** merge this please? And then if you have no objections, we could move it under the  biopython project's GitHub profile (since it is only Biopython talks).

### CODE REVIEW

**Comment by cbrueffer** [comment]
Thanks Peter, I agree this would be valuable to have centrally under the Biopython umbrella.

**Comment by peterjc** [comment]
Right now my personal fork is up to date, and I'll work from there this afternoon on the 2019 abstract.

**Comment by bow** [comment]
Hi @peterjc & @cbrueffer ,

Sure ~ no objections from me on moving it there. I'll rebase this and try to transfer it there.

**Comment by bow** [comment]
Hmm..

GitHub is complaining that I don't have the permissions to create a repository in the biopython group. @peterjc, I guess this means it needs manual clone & push from your end then?

**Comment by peterjc** [comment]
Thank you. Let me get the 2019 abstract done, and then let's work on that.

**Pull request merged**
